/* ===== PURITY LABS INITIAL CATALOG =====
   Real store catalog shipped with the admin panel. Used only as the starting point before the live Firestore data loads; transactional collections (orders, customers, coupons, promotions, reviews, visits) are kept empty. Rebuildable from the deployed product pages via node build.js. */
window.CATALOG = {
  "products": [
    {
      "id": "p01",
      "name": "GLP-3RT",
      "slug": "glp-3rt",
      "cat": "powders",
      "price": 65.99,
      "priceFrom": 54.99,
      "priceTo": 149.99,
      "compare": 0,
      "stock": 25,
      "sku": "PL-GLP3RT",
      "image": "images/glp3rt.png",
      "featured": false,
      "status": "active",
      "desc": "<p>GLP-3RT is a high-purity research compound formulated for laboratory studies. Each vial undergoes rigorous HPLC and Mass Spectrometry testing to verify >99% purity. Supplied as lyophilized powder for reconstitution with bacteriostatic water.</p>",
      "pos": 0,
      "coas": [
        "images/coa-placeholder.svg"
      ],
      "coaEnabled": true,
      "imageHistory": []
    },
    {
      "id": "p02",
      "name": "BACTERIOSTATIC WATER",
      "slug": "bacteriostatic-water",
      "cat": "accessories",
      "price": 23.99,
      "priceFrom": 19.99,
      "priceTo": 55.99,
      "compare": 0,
      "stock": 25,
      "sku": "PL-BACWATER",
      "image": "images/bacteriostaticwater.png",
      "featured": false,
      "status": "active",
      "desc": "<p>Sterile bacteriostatic water for reconstitution of lyophilized research compounds. Each vial is manufactured under strict aseptic conditions and tested for sterility and endotoxin levels.</p>",
      "pos": 1,
      "coas": [
        "images/coa-placeholder.svg"
      ],
      "coaEnabled": true,
      "imageHistory": []
    },
    {
      "id": "p03",
      "name": "GHK-CU",
      "slug": "ghk-cu",
      "cat": "powders",
      "price": 53.99,
      "priceFrom": 44.99,
      "priceTo": 74.99,
      "compare": 0,
      "stock": 25,
      "sku": "PL-GHKCU",
      "image": "images/ghkcu.png",
      "featured": false,
      "status": "active",
      "desc": "<p>GHK-CU is a naturally occurring copper-binding tripeptide with high purity for research applications. Verified >99% via HPLC analysis.</p>",
      "pos": 2,
      "coas": [
        "https://swisschems.is/wp-content/uploads/2026/06/SC-HPLC-GHK-CU-232x300.webp"
      ],
      "coaEnabled": true,
      "imageHistory": []
    },
    {
      "id": "p04",
      "name": "TESAMORELIN",
      "slug": "tesamorelin",
      "cat": "powders",
      "price": 60,
      "priceFrom": 50,
      "priceTo": 139,
      "compare": 0,
      "stock": 25,
      "sku": "PL-TESA",
      "image": "images/tesamorelin.png",
      "featured": false,
      "status": "active",
      "desc": "<p>Tesamorelin is a synthetic growth hormone-releasing hormone analog for laboratory research. Manufactured under GMP conditions with documented chain of custody.</p>",
      "pos": 3,
      "coas": [
        "images/coa-placeholder.svg"
      ],
      "coaEnabled": true,
      "imageHistory": []
    },
    {
      "id": "p05",
      "name": "KPV",
      "slug": "kpv",
      "cat": "powders",
      "price": 53.99,
      "priceFrom": 44.99,
      "priceTo": 119.99,
      "compare": 0,
      "stock": 25,
      "sku": "PL-KPV",
      "image": "images/kpv.png",
      "featured": false,
      "status": "active",
      "desc": "<p>KPV is an alpha-MSH derived tripeptide with high purity for controlled laboratory studies. Each batch independently tested and certified.</p>",
      "pos": 4,
      "coas": [
        "images/coa-placeholder.svg"
      ],
      "coaEnabled": true,
      "imageHistory": []
    },
    {
      "id": "p06",
      "name": "GLUTATHIONE",
      "slug": "glutathione",
      "cat": "powders",
      "price": 48,
      "priceFrom": 40,
      "priceTo": 89.99,
      "compare": 0,
      "stock": 25,
      "sku": "PL-GLUTA",
      "image": "images/glutathione.png",
      "featured": false,
      "status": "active",
      "desc": "<p>Reduced Glutathione (GSH) for biochemical and pharmacological research applications. Verified >99% purity via HPLC and Mass Spectrometry.</p>",
      "pos": 5,
      "coas": [
        "images/coa-placeholder.svg"
      ],
      "coaEnabled": true,
      "imageHistory": []
    },
    {
      "id": "p07",
      "name": "KLOW",
      "slug": "klow",
      "cat": "powders",
      "price": 126,
      "priceFrom": 126,
      "priceTo": 0,
      "compare": 0,
      "stock": 25,
      "sku": "PL-KLOW",
      "image": "images/klow.png",
      "featured": false,
      "status": "active",
      "desc": "<p>KLOW is a premium research compound formulated for advanced laboratory studies. Each vial undergoes rigorous quality verification.</p>",
      "pos": 6,
      "coas": [
        "images/coa-placeholder.svg"
      ],
      "coaEnabled": true,
      "imageHistory": []
    },
    {
      "id": "p08",
      "name": "MOTS-C",
      "slug": "mots-c",
      "cat": "powders",
      "price": 65.99,
      "priceFrom": 54.99,
      "priceTo": 139.99,
      "compare": 0,
      "stock": 25,
      "sku": "PL-MOTSC",
      "image": "images/motsc.png",
      "featured": false,
      "status": "active",
      "desc": "<p>MOTS-C is a mitochondrial-derived peptide for metabolic and exercise-related research. Manufactured under strict GMP conditions with full traceability.</p>",
      "pos": 7,
      "coas": [
        "https://swisschems.is/wp-content/uploads/2026/06/SC-HPLC-MOTS-C-232x300.webp"
      ],
      "coaEnabled": true,
      "imageHistory": []
    },
    {
      "id": "p09",
      "name": "TB-500",
      "slug": "tb-500",
      "cat": "powders",
      "price": 39.99,
      "priceFrom": 39.99,
      "priceTo": 0,
      "compare": 0,
      "stock": 25,
      "sku": "PL-TB500",
      "image": "images/tb500.webp",
      "featured": false,
      "status": "active",
      "desc": "<p>TB-500, also known as Thymosin Beta-4, is a 43-amino acid peptide studied for its role in actin binding and cellular regulation. Research has investigated its capacity to promote angiogenesis, cell migration, and tissue regeneration pathways in laboratory models.</p>\n            <p>All Purity Labs compounds are manufactured under strict GMP conditions. Each batch is independently tested via HPLC and Mass Spectrometry to verify >99% purity and correct molecular composition.</p>",
      "pos": 8,
      "coas": [
        "https://swisschems.is/wp-content/uploads/2026/06/SC-TB-500-Thymosin-Beta-4-5mg-CY07-A-Janoshik-3.webp",
        "https://swisschems.is/wp-content/uploads/2026/06/SC-TB-500-Thymosin-Beta-4-5mg-CY07-A-Janoshik.webp",
        "https://swisschems.is/wp-content/uploads/2026/06/SC-TB-500-Thymosin-Beta-4-5mg-CY07-A-Janoshik-1.webp"
      ],
      "coaEnabled": true,
      "imageHistory": []
    },
    {
      "id": "p10",
      "name": "NAD+",
      "slug": "nad-plus",
      "cat": "powders",
      "price": 69.99,
      "priceFrom": 69.99,
      "priceTo": 0,
      "compare": 0,
      "stock": 25,
      "sku": "PL-NAD",
      "image": "images/nad.webp",
      "featured": false,
      "status": "active",
      "desc": "<p>NAD+ (Nicotinamide Adenine Dinucleotide) is a coenzyme central to cellular energy metabolism and redox reactions. Research examines its role in mitochondrial function, cellular repair mechanisms, and metabolic signaling pathways.</p>\n            <p>All Purity Labs compounds are manufactured under strict GMP conditions. Each batch is independently tested via HPLC and Mass Spectrometry to verify >99% purity and correct molecular composition.</p>",
      "pos": 9,
      "coas": [
        "images/coa-placeholder.svg"
      ],
      "coaEnabled": true,
      "imageHistory": []
    },
    {
      "id": "p11",
      "name": "AOD-9604",
      "slug": "aod-9604",
      "cat": "powders",
      "price": 49.99,
      "priceFrom": 49.99,
      "priceTo": 0,
      "compare": 0,
      "stock": 25,
      "sku": "PL-AOD9604",
      "image": "images/aod9604.webp",
      "featured": false,
      "status": "active",
      "desc": "<p>AOD-9604 is a synthetic peptide fragment derived from the C-terminal region of human growth hormone (hGH 177-191). Research has investigated its potential effects on lipolysis and fat metabolism pathways in experimental settings.</p>\n            <p>All Purity Labs compounds are manufactured under strict GMP conditions. Each batch is independently tested via HPLC and Mass Spectrometry to verify >99% purity and correct molecular composition.</p>",
      "pos": 10,
      "coas": [
        "images/coa-placeholder.svg"
      ],
      "coaEnabled": true,
      "imageHistory": []
    },
    {
      "id": "p12",
      "name": "Ipamorelin",
      "slug": "ipamorelin",
      "cat": "powders",
      "price": 49.99,
      "priceFrom": 49.99,
      "priceTo": 0,
      "compare": 0,
      "stock": 25,
      "sku": "PL-IPAM",
      "image": "images/ipamorelin.svg",
      "featured": false,
      "status": "active",
      "desc": "<p>Ipamorelin is a pentapeptide growth hormone secretagogue studied for its selective stimulation of the growth hormone pathway. Research explores its specificity and comparatively moderate release profile in laboratory investigations.</p>\n            <p>All Purity Labs compounds are manufactured under strict GMP conditions. Each batch is independently tested via HPLC and Mass Spectrometry to verify >99% purity and correct molecular composition.</p>",
      "pos": 11,
      "coas": [
        "https://swisschems.is/wp-content/uploads/2026/06/SC-Ipamorelin-ED9630-Janoshik.webp"
      ],
      "coaEnabled": true,
      "imageHistory": []
    },
    {
      "id": "p13",
      "name": "IGF-1 LR3",
      "slug": "igf-1-lr3",
      "cat": "powders",
      "price": 69.99,
      "priceFrom": 69.99,
      "priceTo": 0,
      "compare": 0,
      "stock": 25,
      "sku": "PL-IGF1",
      "image": "images/igf1lr3.svg",
      "featured": false,
      "status": "active",
      "desc": "<p>IGF-1 LR3 is a long-acting analog of Insulin-like Growth Factor 1 engineered for extended bioactivity. Research investigates its binding characteristics and downstream anabolic signaling relative to native IGF-1.</p>\n            <p>All Purity Labs compounds are manufactured under strict GMP conditions. Each batch is independently tested via HPLC and Mass Spectrometry to verify >99% purity and correct molecular composition.</p>",
      "pos": 12,
      "coas": [
        "https://swisschems.is/wp-content/uploads/2026/06/SC-HPLC-IGF-1-LR3-AY0669-232x300.webp"
      ],
      "coaEnabled": true,
      "imageHistory": []
    },
    {
      "id": "p14",
      "name": "Cagrilintide",
      "slug": "cagrilintide",
      "cat": "powders",
      "price": 69.99,
      "priceFrom": 69.99,
      "priceTo": 0,
      "compare": 0,
      "stock": 25,
      "sku": "PL-CAGRI",
      "image": "images/cagrilintide.svg",
      "featured": false,
      "status": "active",
      "desc": "<p>Cagrilintide is a long-acting amylin analog peptide under research for metabolic regulation pathways. Studies explore its interactions with amylin receptor systems and appetite-regulating mechanisms.</p>\n            <p>All Purity Labs compounds are manufactured under strict GMP conditions. Each batch is independently tested via HPLC and Mass Spectrometry to verify >99% purity and correct molecular composition.</p>",
      "pos": 13,
      "coas": [
        "images/coa-placeholder.svg"
      ],
      "coaEnabled": true,
      "imageHistory": []
    },
    {
      "id": "p15",
      "name": "Epithalon",
      "slug": "epithalon",
      "cat": "powders",
      "price": 29.99,
      "priceFrom": 29.99,
      "priceTo": 0,
      "compare": 0,
      "stock": 25,
      "sku": "PL-EPITH",
      "image": "images/epithalon.svg",
      "featured": false,
      "status": "active",
      "desc": "<p>Epithalon (Epitalon) is a tetrapeptide with the sequence Ala-Glu-Asp-Gly, studied for its effects on telomere maintenance and longevity-related cellular pathways in experimental research models.</p>\n            <p>All Purity Labs compounds are manufactured under strict GMP conditions. Each batch is independently tested via HPLC and Mass Spectrometry to verify >99% purity and correct molecular composition.</p>",
      "pos": 14,
      "coas": [
        "images/coa-placeholder.svg"
      ],
      "coaEnabled": true,
      "imageHistory": []
    },
    {
      "id": "p16",
      "name": "5-Amino-1MQ",
      "slug": "5-amino-1mq",
      "cat": "powders",
      "price": 49.99,
      "priceFrom": 49.99,
      "priceTo": 0,
      "compare": 0,
      "stock": 25,
      "sku": "PL-1MQ",
      "image": "images/amino1mq.svg",
      "featured": false,
      "status": "active",
      "desc": "<p>5-Amino-1MQ (5-Amino-1-Methylquinolinium) is a small molecule NMNAT inhibitor under research for NAD+ metabolism and cellular energy pathways. Studies investigate its influence on metabolic enzyme activity.</p>\n            <p>All Purity Labs compounds are manufactured under strict GMP conditions. Each batch is independently tested via HPLC and Mass Spectrometry to verify >99% purity and correct molecular composition.</p>",
      "pos": 15,
      "coas": [
        "https://swisschems.is/wp-content/uploads/2026/06/SC-HPLC-5-Amino-1MQ-CAPS-0304-1-232x300.webp"
      ],
      "coaEnabled": true,
      "imageHistory": []
    },
    {
      "id": "p17",
      "name": "Melanotan I",
      "slug": "melanotan-i",
      "cat": "powders",
      "price": 29.95,
      "priceFrom": 29.95,
      "priceTo": 0,
      "compare": 0,
      "stock": 25,
      "sku": "PL-MT1",
      "image": "images/melanotani.svg",
      "featured": false,
      "status": "active",
      "desc": "<p>Melanotan I is a synthetic analog of alpha-melanocyte stimulating hormone designed for enhanced stability. Research investigates melanocortin receptor activation and pigment-related signaling pathways.</p>\n            <p>All Purity Labs compounds are manufactured under strict GMP conditions. Each batch is independently tested via HPLC and Mass Spectrometry to verify >99% purity and correct molecular composition.</p>",
      "pos": 16,
      "coas": [
        "images/coa-placeholder.svg"
      ],
      "coaEnabled": true,
      "imageHistory": []
    },
    {
      "id": "p18",
      "name": "Thymosin Alpha-1",
      "slug": "thymosin-alpha-1",
      "cat": "powders",
      "price": 39.99,
      "priceFrom": 39.99,
      "priceTo": 0,
      "compare": 0,
      "stock": 25,
      "sku": "PL-TA1",
      "image": "images/thymosinalpha1.svg",
      "featured": false,
      "status": "active",
      "desc": "<p>Thymosin Alpha-1 (Thymalfasin) is a 28-amino acid peptide derived from the thymus studied for immune regulatory functions. Research explores its modulation of T-cell development and immune response cascades.</p>\n            <p>All Purity Labs compounds are manufactured under strict GMP conditions. Each batch is independently tested via HPLC and Mass Spectrometry to verify >99% purity and correct molecular composition.</p>",
      "pos": 17,
      "coas": [
        "https://swisschems.is/wp-content/uploads/2026/06/SC-HPLC-Thymosin-Alpha-1-232x300.webp"
      ],
      "coaEnabled": true,
      "imageHistory": []
    },
    {
      "id": "p19",
      "name": "SNAP-8",
      "slug": "snap-8",
      "cat": "powders",
      "price": 29.99,
      "priceFrom": 29.99,
      "priceTo": 0,
      "compare": 0,
      "stock": 25,
      "sku": "PL-SNAP8",
      "image": "images/snap8.svg",
      "featured": false,
      "status": "active",
      "desc": "<p>SNAP-8 (Acetyl Octapeptide-3) is a synthetic octapeptide designed to modulate SNARE complex function. Research studies its effects on neurotransmitter release signaling at the cellular level.</p>\n            <p>All Purity Labs compounds are manufactured under strict GMP conditions. Each batch is independently tested via HPLC and Mass Spectrometry to verify >99% purity and correct molecular composition.</p>",
      "pos": 18,
      "coas": [
        "images/coa-placeholder.svg"
      ],
      "coaEnabled": true,
      "imageHistory": []
    },
    {
      "id": "p20",
      "name": "Sermorelin",
      "slug": "sermorelin",
      "cat": "powders",
      "price": 59.99,
      "priceFrom": 59.99,
      "priceTo": 0,
      "compare": 0,
      "stock": 25,
      "sku": "PL-SERMO",
      "image": "images/sermorelin.svg",
      "featured": false,
      "status": "active",
      "desc": "<p>Sermorelin is a synthetic analog of growth hormone-releasing hormone (GHRH 1-29). Research examines its selective stimulation of endogenous growth hormone release pathways.</p>\n            <p>All Purity Labs compounds are manufactured under strict GMP conditions. Each batch is independently tested via HPLC and Mass Spectrometry to verify >99% purity and correct molecular composition.</p>",
      "pos": 19,
      "coas": [
        "https://swisschems.is/wp-content/uploads/2026/06/SC-Sermorelin-CY8166-Janoshik.webp"
      ],
      "coaEnabled": true,
      "imageHistory": []
    },
    {
      "id": "p21",
      "name": "Dihexa",
      "slug": "dihexa",
      "cat": "powders",
      "price": 59.99,
      "priceFrom": 59.99,
      "priceTo": 0,
      "compare": 0,
      "stock": 25,
      "sku": "PL-DIHEXA",
      "image": "images/dihexa.svg",
      "featured": false,
      "status": "active",
      "desc": "<p>Dihexa is a synthetic small molecule peptide mimetic studied for its promotion of synapse formation. Research investigates its binding to hepatocyte growth factor receptors and neurite outgrowth activity.</p>\n            <p>All Purity Labs compounds are manufactured under strict GMP conditions. Each batch is independently tested via HPLC and Mass Spectrometry to verify >99% purity and correct molecular composition.</p>",
      "pos": 20,
      "coas": [
        "https://swisschems.is/wp-content/uploads/2026/06/SC-HPLC-Dihexa-CAPS-232x300.webp"
      ],
      "coaEnabled": true,
      "imageHistory": []
    },
    {
      "id": "p22",
      "name": "ARA-290",
      "slug": "ara-290",
      "cat": "powders",
      "price": 49.99,
      "priceFrom": 49.99,
      "priceTo": 0,
      "compare": 0,
      "stock": 25,
      "sku": "PL-ARA290",
      "image": "images/ara290.svg",
      "featured": false,
      "status": "active",
      "desc": "<p>ARA-290 is an 11-amino acid erythropoietin-derived peptide designed to target tissue-protective receptor complexes. Research explores its anti-inflammatory and neuroprotective signaling properties.</p>\n            <p>All Purity Labs compounds are manufactured under strict GMP conditions. Each batch is independently tested via HPLC and Mass Spectrometry to verify >99% purity and correct molecular composition.</p>",
      "pos": 21,
      "coas": [
        "https://swisschems.is/wp-content/uploads/2026/06/SC-HPLC-ARA290-232x300.webp"
      ],
      "coaEnabled": true,
      "imageHistory": []
    },
    {
      "id": "p23",
      "name": "Kisspeptin",
      "slug": "kisspeptin",
      "cat": "powders",
      "price": 49.99,
      "priceFrom": 49.99,
      "priceTo": 0,
      "compare": 0,
      "stock": 25,
      "sku": "PL-KISS",
      "image": "images/kisspeptin.svg",
      "featured": false,
      "status": "active",
      "desc": "<p>Kisspeptin is a peptide hormone encoded by the KISS1 gene that acts as a key regulator of reproductive axis signaling. Research examines its role in GnRH neuron activation and hormone cascade pathways.</p>\n            <p>All Purity Labs compounds are manufactured under strict GMP conditions. Each batch is independently tested via HPLC and Mass Spectrometry to verify >99% purity and correct molecular composition.</p>",
      "pos": 22,
      "coas": [
        "https://swisschems.is/wp-content/uploads/2026/06/SC-HPLC-Kisspeptin-10-232x300.webp"
      ],
      "coaEnabled": true,
      "imageHistory": []
    },
    {
      "id": "p24",
      "name": "VIP",
      "slug": "vip",
      "cat": "powders",
      "price": 49.99,
      "priceFrom": 49.99,
      "priceTo": 0,
      "compare": 0,
      "stock": 25,
      "sku": "PL-VIP",
      "image": "images/vip.svg",
      "featured": false,
      "status": "active",
      "desc": "<p>VIP (Vasoactive Intestinal Peptide) is a 28-amino acid neuropeptide with broad signaling functions. Research studies its anti-inflammatory, immunomodulatory, and neuroprotective roles in experimental systems.</p>\n            <p>All Purity Labs compounds are manufactured under strict GMP conditions. Each batch is independently tested via HPLC and Mass Spectrometry to verify >99% purity and correct molecular composition.</p>",
      "pos": 23,
      "coas": [
        "images/coa-placeholder.svg"
      ],
      "coaEnabled": true,
      "imageHistory": []
    },
    {
      "id": "p25",
      "name": "GLP-2",
      "slug": "glp-2",
      "cat": "powders",
      "price": 59.99,
      "priceFrom": 59.99,
      "priceTo": 0,
      "compare": 0,
      "stock": 25,
      "sku": "PL-GLP2",
      "image": "images/glp2.svg",
      "featured": false,
      "status": "active",
      "desc": "<p>GLP-2 (Glucagon-Like Peptide 2) is a 33-amino acid incretin peptide studied for gut health signaling. Research explores its effects on intestinal cell proliferation and nutrient absorption pathways.</p>\n            <p>All Purity Labs compounds are manufactured under strict GMP conditions. Each batch is independently tested via HPLC and Mass Spectrometry to verify >99% purity and correct molecular composition.</p>",
      "pos": 24,
      "coas": [
        "images/coa-placeholder.svg"
      ],
      "coaEnabled": true,
      "imageHistory": []
    },
    {
      "id": "p26",
      "name": "GLP-1",
      "slug": "glp-1",
      "cat": "powders",
      "price": 49.99,
      "priceFrom": 49.99,
      "priceTo": 0,
      "compare": 0,
      "stock": 25,
      "sku": "PL-GLP1",
      "image": "images/glp1.svg",
      "featured": false,
      "status": "active",
      "desc": "<p>GLP-1 (Glucagon-Like Peptide 1) is a 30-amino acid incretin hormone studied for metabolic signaling. Research investigates its receptor activation and effects on insulin secretion and glucose homeostasis.</p>\n            <p>All Purity Labs compounds are manufactured under strict GMP conditions. Each batch is independently tested via HPLC and Mass Spectrometry to verify >99% purity and correct molecular composition.</p>",
      "pos": 25,
      "coas": [
        "images/coa-placeholder.svg"
      ],
      "coaEnabled": true,
      "imageHistory": []
    },
    {
      "id": "p27",
      "name": "AHK-Cu",
      "slug": "ahk-cu",
      "cat": "powders",
      "price": 34.99,
      "priceFrom": 34.99,
      "priceTo": 0,
      "compare": 0,
      "stock": 25,
      "sku": "PL-AHK",
      "image": "images/ahkcu.svg",
      "featured": false,
      "status": "active",
      "desc": "<p>AHK-Cu is a copper-binding tripeptide analog studied alongside GHK-Cu for metal ion coordination. Research explores its copper delivery, antioxidant, and extracellular matrix remodeling characteristics.</p>\n            <p>All Purity Labs compounds are manufactured under strict GMP conditions. Each batch is independently tested via HPLC and Mass Spectrometry to verify >99% purity and correct molecular composition.</p>",
      "pos": 26,
      "coas": [
        "images/coa-placeholder.svg"
      ],
      "coaEnabled": true,
      "imageHistory": []
    },
    {
      "id": "p28",
      "name": "Pinealon",
      "slug": "pinealon",
      "cat": "powders",
      "price": 49.99,
      "priceFrom": 49.99,
      "priceTo": 0,
      "compare": 0,
      "stock": 25,
      "sku": "PL-PINE",
      "image": "images/pinealon.svg",
      "featured": false,
      "status": "active",
      "desc": "<p>Pinealon is a synthetic tripeptide studied for neuroprotective properties. Research examines its influence on oxidative stress resistance and neuronal survival signaling in experimental models.</p>\n            <p>All Purity Labs compounds are manufactured under strict GMP conditions. Each batch is independently tested via HPLC and Mass Spectrometry to verify >99% purity and correct molecular composition.</p>",
      "pos": 27,
      "coas": [
        "images/coa-placeholder.svg"
      ],
      "coaEnabled": true,
      "imageHistory": []
    },
    {
      "id": "p29",
      "name": "LL-37",
      "slug": "ll-37",
      "cat": "powders",
      "price": 34.99,
      "priceFrom": 34.99,
      "priceTo": 0,
      "compare": 0,
      "stock": 25,
      "sku": "PL-LL37",
      "image": "images/ll37.svg",
      "featured": false,
      "status": "active",
      "desc": "<p>LL-37 is a 37-amino acid cathelicidin antimicrobial peptide with broad-spectrum activity. Research investigates its antimicrobial, immunomodulatory, and wound-healing signaling functions.</p>\n            <p>All Purity Labs compounds are manufactured under strict GMP conditions. Each batch is independently tested via HPLC and Mass Spectrometry to verify >99% purity and correct molecular composition.</p>",
      "pos": 28,
      "coas": [
        "images/coa-placeholder.svg"
      ],
      "coaEnabled": true,
      "imageHistory": []
    },
    {
      "id": "p30",
      "name": "Cartalax",
      "slug": "cartalax",
      "cat": "powders",
      "price": 69.99,
      "priceFrom": 69.99,
      "priceTo": 0,
      "compare": 0,
      "stock": 25,
      "sku": "PL-CARTA",
      "image": "images/cartalax.svg",
      "featured": false,
      "status": "active",
      "desc": "<p>Cartalax is a peptide blend formulated for cartilage and joint research applications. Research explores its potential role in extracellular matrix maintenance and connective tissue signaling pathways.</p>\n            <p>All Purity Labs compounds are manufactured under strict GMP conditions. Each batch is independently tested via HPLC and Mass Spectrometry to verify >99% purity and correct molecular composition.</p>",
      "pos": 29,
      "coas": [
        "images/coa-placeholder.svg"
      ],
      "coaEnabled": true,
      "imageHistory": []
    },
    {
      "id": "p31",
      "name": "CJC-1295 / Ipamorelin",
      "slug": "cjc-ipa",
      "cat": "powders",
      "price": 59.99,
      "priceFrom": 59.99,
      "priceTo": 0,
      "compare": 0,
      "stock": 25,
      "sku": "PL-CJCI",
      "image": "images/cjcipa.svg",
      "featured": false,
      "status": "active",
      "desc": "<p>CJC-1295 (No DAC) with Ipamorelin is a research blend combining a modified growth hormone-releasing hormone with a selective secretagogue. Studies examine their complementary actions on growth hormone signaling pathways.</p>\n            <p>All Purity Labs compounds are manufactured under strict GMP conditions. Each batch is independently tested via HPLC and Mass Spectrometry to verify >99% purity and correct molecular composition.</p>",
      "pos": 30,
      "coas": [
        "https://swisschems.is/wp-content/uploads/2026/06/SC-HPLC-CJC-1295-without-DAC-CY-15A-232x300.webp"
      ],
      "coaEnabled": true,
      "imageHistory": []
    },
    {
      "id": "p32",
      "name": "BPC-157/TB-500",
      "slug": "wolverine",
      "cat": "powders",
      "price": 79.99,
      "priceFrom": 79.99,
      "priceTo": 0,
      "compare": 0,
      "stock": 25,
      "sku": "PL-WOLV",
      "image": "images/wolverine.svg",
      "featured": false,
      "status": "active",
      "desc": "<p>BPC-157/TB-500 (Wolverine) is a stacked research peptide blend combining Body Protection Compound-157 with Thymosin Beta-4. The pairing is studied for complementary regenerative and anti-inflammatory signaling pathways.</p>\n            <p>All Purity Labs compounds are manufactured under strict GMP conditions. Each batch is independently tested via HPLC and Mass Spectrometry to verify >99% purity and correct molecular composition.</p>",
      "pos": 31,
      "coas": [
        "https://swisschems.is/wp-content/uploads/2026/06/SC-TBPC-157-5mg-TB-500-5mg-Blend-ED3059-Janoshik-4.webp",
        "https://swisschems.is/wp-content/uploads/2026/06/SC-TBPC-157-5mg-TB-500-5mg-Blend-ED3059-Janoshik-5.webp",
        "https://swisschems.is/wp-content/uploads/2026/06/SC-BPC-157-5mg-TB-500-5mg-Blend-ED3059-Janoshik-1.webp",
        "https://swisschems.is/wp-content/uploads/2026/06/SC-BPC-157-5mg-TB-500-5mg-Blend-ED3059-Janoshik-2.webp",
        "https://swisschems.is/wp-content/uploads/2026/06/SC-TBPC-157-5mg-TB-500-5mg-Blend-ED3059-Janoshik.webp",
        "https://swisschems.is/wp-content/uploads/2026/06/SC-TBPC-157-5mg-TB-500-5mg-Blend-Heavy-Metal-Janoshik.webp"
      ],
      "coaEnabled": true,
      "imageHistory": []
    },
    {
      "id": "p33",
      "name": "GLOW",
      "slug": "glow",
      "cat": "powders",
      "price": 89.99,
      "priceFrom": 89.99,
      "priceTo": 0,
      "compare": 0,
      "stock": 25,
      "sku": "PL-GLOW",
      "image": "images/glow.svg",
      "featured": false,
      "status": "active",
      "desc": "<p>GLOW is a triple regenerative research stack combining BPC-157, TB-500, and GHK-Cu. The formulation is designed to investigate complementary pathways in cellular migration, angiogenesis, and extracellular matrix remodeling.</p>\n            <p>All Purity Labs compounds are manufactured under strict GMP conditions. Each batch is independently tested via HPLC and Mass Spectrometry to verify >99% purity and correct molecular composition.</p>",
      "pos": 32,
      "coas": [
        "images/coa-placeholder.svg"
      ],
      "coaEnabled": true,
      "imageHistory": []
    },
    {
      "id": "p34",
      "name": "BPC-157 – MIST APPLICATOR",
      "slug": "bpc-157-mist",
      "cat": "sprays",
      "price": 107.99,
      "priceFrom": 107.99,
      "priceTo": 0,
      "compare": 0,
      "stock": 25,
      "sku": "PL-BPC157N",
      "image": "images/bpc.png",
      "featured": false,
      "status": "active",
      "desc": "<p>BPC-157 Mist Applicator delivers high-purity Body Protection Compound-157 in a convenient nasal mist format for research applications. Each applicator contains precisely measured doses verified >99% pure via HPLC analysis.</p>\n            <p>All Purity Labs mist applicators are manufactured under strict GMP conditions. Each batch is independently tested via HPLC and Mass Spectrometry to verify >99% purity and correct molecular composition.</p>",
      "pos": 33,
      "coas": [
        "https://swisschems.is/wp-content/uploads/2026/06/SC-BPC-157-with-Arginine-Salt-5mg-HPLC.webp",
        "https://swisschems.is/wp-content/uploads/2026/06/SC-BPC-157-5748-Janoshik.webp",
        "https://swisschems.is/wp-content/uploads/2026/06/SC-BPC-157-5748-Janoshik-2.webp"
      ],
      "coaEnabled": true,
      "imageHistory": []
    },
    {
      "id": "p35",
      "name": "DSIP – MIST APPLICATOR",
      "slug": "dsip-mist",
      "cat": "sprays",
      "price": 89.99,
      "priceFrom": 89.99,
      "priceTo": 0,
      "compare": 0,
      "stock": 25,
      "sku": "PL-DSIPN",
      "image": "images/dsip.png",
      "featured": false,
      "status": "active",
      "desc": "<p>Delta Sleep-Inducing Peptide (DSIP) mist applicator for neuroscience research applications. Supplied in a sterile nasal mist format with verified purity >99%.</p>\n            <p>All Purity Labs mist applicators are manufactured under strict GMP conditions. Each batch is independently tested via HPLC and Mass Spectrometry to verify >99% purity and correct molecular composition.</p>",
      "pos": 34,
      "coas": [
        "images/coa-placeholder.svg"
      ],
      "coaEnabled": true,
      "imageHistory": []
    },
    {
      "id": "p36",
      "name": "KPV – MIST APPLICATOR",
      "slug": "kpv-mist",
      "cat": "sprays",
      "price": 95.99,
      "priceFrom": 95.99,
      "priceTo": 0,
      "compare": 0,
      "stock": 25,
      "sku": "PL-KPVN",
      "image": "images/kpvnasal.png",
      "featured": false,
      "status": "active",
      "desc": "<p>KPV Mist Applicator provides alpha-MSH derived tripeptide in an intranasal delivery format for controlled laboratory studies. Each unit undergoes rigorous quality verification.</p>\n            <p>All Purity Labs mist applicators are manufactured under strict GMP conditions. Each batch is independently tested via HPLC and Mass Spectrometry to verify >99% purity and correct molecular composition.</p>",
      "pos": 35,
      "coas": [
        "images/coa-placeholder.svg"
      ],
      "coaEnabled": true,
      "imageHistory": []
    },
    {
      "id": "p37",
      "name": "MT-2 – MIST APPLICATOR",
      "slug": "mt2-mist",
      "cat": "sprays",
      "price": 119.99,
      "priceFrom": 119.99,
      "priceTo": 0,
      "compare": 0,
      "stock": 25,
      "sku": "PL-MT2N",
      "image": "images/mt2.png",
      "featured": false,
      "status": "active",
      "desc": "<p>Melanotan II (MT-2) mist applicator for dermatological and tanning research. Delivered via precision nasal mist with documented chain of custody and >99% purity.</p>\n            <p>All Purity Labs mist applicators are manufactured under strict GMP conditions. Each batch is independently tested via HPLC and Mass Spectrometry to verify >99% purity and correct molecular composition.</p>",
      "pos": 36,
      "coas": [
        "https://swisschems.is/wp-content/uploads/2026/06/SC-Melanotan-II-ED3760-Janoshik.webp"
      ],
      "coaEnabled": true,
      "imageHistory": []
    },
    {
      "id": "p38",
      "name": "PT-141 – MIST APPLICATOR",
      "slug": "pt141-mist",
      "cat": "sprays",
      "price": 149.99,
      "priceFrom": 149.99,
      "priceTo": 0,
      "compare": 0,
      "stock": 25,
      "sku": "PL-PT141N",
      "image": "images/pt141.png",
      "featured": false,
      "status": "active",
      "desc": "<p>PT-141 (Bremelanotide) mist applicator for sexual health and melanocortin research. High-purity formulation in sterile nasal mist format.</p>\n            <p>All Purity Labs mist applicators are manufactured under strict GMP conditions. Each batch is independently tested via HPLC and Mass Spectrometry to verify >99% purity and correct molecular composition.</p>",
      "pos": 37,
      "coas": [
        "images/coa-placeholder.svg"
      ],
      "coaEnabled": true,
      "imageHistory": []
    },
    {
      "id": "p39",
      "name": "SELANK – MIST APPLICATOR",
      "slug": "selank-mist",
      "cat": "sprays",
      "price": 79.99,
      "priceFrom": 64.99,
      "priceTo": 109.99,
      "compare": 0,
      "stock": 25,
      "sku": "PL-SELANK",
      "image": "images/selank.png",
      "featured": false,
      "status": "active",
      "desc": "<p>Selank is a synthetic anxiolytic peptide delivered via nasal mist for neurochemical research. Manufactured under GMP conditions with full analytical documentation.</p>\n            <p>All Purity Labs mist applicators are manufactured under strict GMP conditions. Each batch is independently tested via HPLC and Mass Spectrometry to verify >99% purity and correct molecular composition.</p>",
      "pos": 38,
      "coas": [
        "images/coa-placeholder.svg"
      ],
      "coaEnabled": true,
      "imageHistory": []
    },
    {
      "id": "p40",
      "name": "SEMAX – MIST APPLICATOR",
      "slug": "semax-mist",
      "cat": "sprays",
      "price": 79.99,
      "priceFrom": 64.99,
      "priceTo": 109.99,
      "compare": 0,
      "stock": 25,
      "sku": "PL-SEMAX",
      "image": "images/semax.png",
      "featured": false,
      "status": "active",
      "desc": "<p>Semax is a synthetic ACTH analog delivered via nasal mist for cognitive and neuroprotective research. Each batch independently tested and certified >99% pure.</p>\n            <p>All Purity Labs mist applicators are manufactured under strict GMP conditions. Each batch is independently tested via HPLC and Mass Spectrometry to verify >99% purity and correct molecular composition.</p>",
      "pos": 39,
      "coas": [
        "images/coa-placeholder.svg"
      ],
      "coaEnabled": true,
      "imageHistory": []
    },
    {
      "id": "p41",
      "name": "NAD+ Spray",
      "slug": "nad-spray",
      "cat": "sprays",
      "price": 49.99,
      "priceFrom": 49.99,
      "priceTo": 0,
      "compare": 0,
      "stock": 25,
      "sku": "PL-NADN",
      "image": "images/nad.webp",
      "featured": false,
      "status": "active",
      "desc": "<p>NAD+ Spray delivers high-purity Nicotinamide Adenine Dinucleotide in a convenient nasal mist format for research applications. Each applicator contains precisely measured doses verified >99% pure via HPLC analysis.</p>\n            <p>All Purity Labs compounds are manufactured under strict GMP conditions. Each batch is independently tested via HPLC and Mass Spectrometry to verify >99% purity and correct molecular composition.</p>",
      "pos": 40,
      "coas": [
        "images/coa-placeholder.svg"
      ],
      "coaEnabled": true,
      "imageHistory": []
    },
    {
      "id": "p42",
      "name": "GHK-Cu Spray",
      "slug": "ghk-cu-spray",
      "cat": "sprays",
      "price": 49.99,
      "priceFrom": 49.99,
      "priceTo": 0,
      "compare": 0,
      "stock": 25,
      "sku": "PL-GHKCN",
      "image": "images/ghkcu.png",
      "featured": false,
      "status": "active",
      "desc": "<p>GHK-Cu Spray delivers high-purity Copper Tripeptide-1 in a convenient nasal mist format for research applications. Each applicator contains precisely measured doses verified >99% pure via HPLC analysis.</p>\n            <p>All Purity Labs compounds are manufactured under strict GMP conditions. Each batch is independently tested via HPLC and Mass Spectrometry to verify >99% purity and correct molecular composition.</p>",
      "pos": 41,
      "coas": [
        "https://swisschems.is/wp-content/uploads/2026/06/SC-HPLC-GHK-CU-232x300.webp"
      ],
      "coaEnabled": true,
      "imageHistory": []
    },
    {
      "id": "p43",
      "name": "BPC-157/TB-500 Spray",
      "slug": "wolverine-spray",
      "cat": "sprays",
      "price": 99.99,
      "priceFrom": 99.99,
      "priceTo": 0,
      "compare": 0,
      "stock": 25,
      "sku": "PL-WOLVN",
      "image": "images/wolverine.svg",
      "featured": false,
      "status": "active",
      "desc": "<p>BPC-157/TB-500 Spray delivers the Wolverine research blend of Body Protection Compound-157 and Thymosin Beta-4 in a convenient nasal mist format. Each applicator contains precisely measured doses verified >99% pure.</p>\n            <p>All Purity Labs compounds are manufactured under strict GMP conditions. Each batch is independently tested via HPLC and Mass Spectrometry to verify >99% purity and correct molecular composition.</p>",
      "pos": 42,
      "coas": [
        "https://swisschems.is/wp-content/uploads/2026/06/SC-TBPC-157-5mg-TB-500-5mg-Blend-ED3059-Janoshik-4.webp",
        "https://swisschems.is/wp-content/uploads/2026/06/SC-TBPC-157-5mg-TB-500-5mg-Blend-ED3059-Janoshik-5.webp",
        "https://swisschems.is/wp-content/uploads/2026/06/SC-BPC-157-5mg-TB-500-5mg-Blend-ED3059-Janoshik-1.webp",
        "https://swisschems.is/wp-content/uploads/2026/06/SC-BPC-157-5mg-TB-500-5mg-Blend-ED3059-Janoshik-2.webp",
        "https://swisschems.is/wp-content/uploads/2026/06/SC-TBPC-157-5mg-TB-500-5mg-Blend-ED3059-Janoshik.webp",
        "https://swisschems.is/wp-content/uploads/2026/06/SC-TBPC-157-5mg-TB-500-5mg-Blend-Heavy-Metal-Janoshik.webp"
      ],
      "coaEnabled": true,
      "imageHistory": []
    },
    {
      "id": "p44",
      "name": "Adamax Spray",
      "slug": "adamax-spray",
      "cat": "sprays",
      "price": 89.99,
      "priceFrom": 89.99,
      "priceTo": 0,
      "compare": 0,
      "stock": 25,
      "sku": "PL-ADAXN",
      "image": "images/adamax.svg",
      "featured": false,
      "status": "active",
      "desc": "<p>Adamax Spray delivers high-purity Adamax, a dihexa-derived research peptide, in a convenient nasal mist format. Each applicator contains precisely measured doses verified >99% pure via HPLC analysis.</p>\n            <p>All Purity Labs compounds are manufactured under strict GMP conditions. Each batch is independently tested via HPLC and Mass Spectrometry to verify >99% purity and correct molecular composition.</p>",
      "pos": 43,
      "coas": [
        "images/coa-placeholder.svg"
      ],
      "coaEnabled": true,
      "imageHistory": []
    },
    {
      "id": "p45",
      "name": "Adalank Spray",
      "slug": "adalank-spray",
      "cat": "sprays",
      "price": 89.99,
      "priceFrom": 89.99,
      "priceTo": 0,
      "compare": 0,
      "stock": 25,
      "sku": "PL-ADALN",
      "image": "images/adalank.svg",
      "featured": false,
      "status": "active",
      "desc": "<p>Adalank Spray delivers high-purity Adalank in a convenient nasal mist format for research applications. Each applicator contains precisely measured doses verified >99% pure via HPLC analysis.</p>\n            <p>All Purity Labs compounds are manufactured under strict GMP conditions. Each batch is independently tested via HPLC and Mass Spectrometry to verify >99% purity and correct molecular composition.</p>",
      "pos": 44,
      "coas": [
        "images/coa-placeholder.svg"
      ],
      "coaEnabled": true,
      "imageHistory": []
    }
  ],
  "categories": [
    {
      "id": "powders",
      "name": "Peptides (Powder)",
      "slug": "peptides"
    },
    {
      "id": "sprays",
      "name": "Nasal Sprays & Mists",
      "slug": "nasal-sprays"
    },
    {
      "id": "accessories",
      "name": "Accessories",
      "slug": "accessories"
    }
  ],
  "nav": [
    {
      "id": "n1",
      "label": "All Peptides",
      "url": "#products",
      "pos": 0
    },
    {
      "id": "n2",
      "label": "COAs",
      "url": "pages/coas.html",
      "pos": 1
    },
    {
      "id": "n3",
      "label": "About Us",
      "url": "pages/about.html",
      "pos": 2
    },
    {
      "id": "n4",
      "label": "info@puritylabs.org",
      "url": "mailto:info@puritylabs.org",
      "pos": 3
    },
    {
      "id": "nd1",
      "label": "Shop All Peptides",
      "url": "#products",
      "pos": 100
    },
    {
      "id": "nd2",
      "label": "Nasal Sprays",
      "url": "pages/nasal-sprays.html",
      "pos": 101
    },
    {
      "id": "nd3",
      "label": "Pills",
      "url": "#products",
      "pos": 102
    }
  ],
  "content": {
    "siteName": "Purity Labs",
    "tagline": "Premium Research Peptides",
    "topbar": "FREE SHIPPING STARTS AT $250",
    "heroTitle": "Precision Research Compounds",
    "heroSubtitle": "For In Vitro Research Use Only",
    "heroBtn": "SHOP PEPTIDES",
    "heroUrl": "#products",
    "footerAbout": "Ultra-pure amino acid derivatives and proteins manufactured for the research community. Thoroughly analyzed, certified >99% purity.",
    "trust1": "VERIFIED >99% PURITY",
    "trust1S": "Every compound undergoes comprehensive testing via HPLC and Mass Spectrometry.",
    "trust2": "SECURE SHIPPING",
    "trust2S": "Your laboratory materials arrive in protected packaging.",
    "trust3": "DEDICATED SUPPORT",
    "trust3S": "Knowledgeable team members available for research inquiries.",
    "trust4": "Support",
    "trust4S": "Fast, human answers",
    "contactEmail": "info@puritylabs.org",
    "contactPhone": "+1 (888) 555-0134",
    "contactAddress": "2520 Research Blvd, Suite B, Las Vegas, NV",
    "announcement": "Summer launch: KLOW now in stock.",
    "announcementLabel": "NEW"
  },
  "settings": {
    "currency": "USD $",
    "freeShipThreshold": 250,
    "flatRate": 9.99,
    "taxRate": 0,
    "lowStockAlert": 10,
    "ordersPerPage": 10,
    "emailFrom": "no-reply@puritylabs.com",
    "returnsPolicy": "Returns accepted within 14 days of delivery for unopened, sealed products. Contact support for an RMA number.",
    "terms": "Research use only. Products are not intended for human consumption."
  }
};
